#!/bin/bash -x

if [ -z $1 ]
  then
    if [ -z $ARTIFACTORY_URL ]
      then
        echo "Usage: publish-artifactory <artifactory_url> (e.g. https://example.org/artifactory)"
        echo " ... or set the ARTIFACTORY_URL environment variable"
        exit 1
    fi
else
  ARTIFACTORY_URL=$1
fi

sbt -Dsbt.override.publish.repos.release=$ARTIFACTORY_URL/general \
    -Dsbt.override.publish.repos.snapshot=$ARTIFACTORY_URL/general-snapshots \
    "set credentials in Global += Credentials(Path.userHome / \".artifactory_credentials\")" \
    "publishSigned"